
package com.example.wsservice.jax_ws.cxf.client.wsdl;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.3.5
 * 2020-03-21T23:21:14.432+08:00
 * Generated source version: 3.3.5
 *
 */
public final class WebServiceI_WebServiceIPort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.cxf.wsservice.example.com/", "WebServiceIService");

    private WebServiceI_WebServiceIPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = WebServiceIService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        WebServiceIService ss = new WebServiceIService(wsdlURL, SERVICE_NAME);
        WebServiceI port = ss.getWebServiceIPort();

        {
        System.out.println("Invoking sayHello...");
        java.lang.String _sayHello_arg0 = "";
        java.lang.String _sayHello__return = port.sayHello(_sayHello_arg0);
        System.out.println("sayHello.result=" + _sayHello__return);


        }
        {
        System.out.println("Invoking webserviceSave...");
        java.lang.String _webserviceSave_arg0 = "";
        java.lang.String _webserviceSave_arg1 = "";
        java.lang.String _webserviceSave__return = port.webserviceSave(_webserviceSave_arg0, _webserviceSave_arg1);
        System.out.println("webserviceSave.result=" + _webserviceSave__return);


        }

        System.exit(0);
    }

}
